/*
Exasol SaaS REST-API

## Authentication  The REST API can be used with your Personal Access Token (PAT). You don't know what a PAT is, check our documentation  [here](https://docs.exasol.com/saas/administration/access_mngt/access_token.htm).  After you created a PAT click on Authorize and add your PAT under BearerAuth.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateDatabase struct for UpdateDatabase
type UpdateDatabase struct {
	Name string `json:"name"`
}

// NewUpdateDatabase instantiates a new UpdateDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDatabase(name string) *UpdateDatabase {
	this := UpdateDatabase{}
	this.Name = name
	return &this
}

// NewUpdateDatabaseWithDefaults instantiates a new UpdateDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDatabaseWithDefaults() *UpdateDatabase {
	this := UpdateDatabase{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateDatabase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateDatabase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateDatabase) SetName(v string) {
	o.Name = v
}

func (o UpdateDatabase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateDatabase struct {
	value *UpdateDatabase
	isSet bool
}

func (v NullableUpdateDatabase) Get() *UpdateDatabase {
	return v.value
}

func (v *NullableUpdateDatabase) Set(val *UpdateDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDatabase(val *UpdateDatabase) *NullableUpdateDatabase {
	return &NullableUpdateDatabase{value: val, isSet: true}
}

func (v NullableUpdateDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
