/*
Exasol SaaS REST-API

## Authentication  The REST API can be used with your Personal Access Token (PAT). You don't know what a PAT is, check our documentation  [here](https://docs.exasol.com/saas/administration/access_mngt/access_token.htm).  After you created a PAT click on Authorize and add your PAT under BearerAuth.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Integrations struct for Integrations
type Integrations struct {
	Id   string  `json:"id"`
	Name string  `json:"name"`
	Url  *string `json:"url,omitempty"`
}

// NewIntegrations instantiates a new Integrations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrations(id string, name string) *Integrations {
	this := Integrations{}
	this.Id = id
	this.Name = name
	return &this
}

// NewIntegrationsWithDefaults instantiates a new Integrations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationsWithDefaults() *Integrations {
	this := Integrations{}
	return &this
}

// GetId returns the Id field value
func (o *Integrations) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Integrations) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Integrations) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Integrations) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Integrations) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Integrations) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Integrations) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Integrations) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Integrations) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Integrations) SetUrl(v string) {
	o.Url = &v
}

func (o Integrations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrations struct {
	value *Integrations
	isSet bool
}

func (v NullableIntegrations) Get() *Integrations {
	return v.value
}

func (v *NullableIntegrations) Set(val *Integrations) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrations) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrations(val *Integrations) *NullableIntegrations {
	return &NullableIntegrations{value: val, isSet: true}
}

func (v NullableIntegrations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
