/*
Exasol SaaS REST-API

## Authentication  The REST API can be used with your Personal Access Token (PAT). You don't know what a PAT is, check our documentation  [here](https://docs.exasol.com/saas/administration/access_mngt/access_token.htm).  After you created a PAT click on Authorize and add your PAT under BearerAuth.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserDatabase struct for UserDatabase
type UserDatabase struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// NewUserDatabase instantiates a new UserDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDatabase(id string, name string) *UserDatabase {
	this := UserDatabase{}
	this.Id = id
	this.Name = name
	return &this
}

// NewUserDatabaseWithDefaults instantiates a new UserDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDatabaseWithDefaults() *UserDatabase {
	this := UserDatabase{}
	return &this
}

// GetId returns the Id field value
func (o *UserDatabase) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserDatabase) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserDatabase) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *UserDatabase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserDatabase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserDatabase) SetName(v string) {
	o.Name = v
}

func (o UserDatabase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableUserDatabase struct {
	value *UserDatabase
	isSet bool
}

func (v NullableUserDatabase) Get() *UserDatabase {
	return v.value
}

func (v *NullableUserDatabase) Set(val *UserDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDatabase(val *UserDatabase) *NullableUserDatabase {
	return &NullableUserDatabase{value: val, isSet: true}
}

func (v NullableUserDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
