openapi: 3.0.0
info:
  description: "## Authentication\n\nThe REST API can be used with your Personal Access\
    \ Token (PAT). You don't know what a PAT is, check our documentation \n[here](https://docs.exasol.com/saas/administration/access_mngt/access_token.htm).\n\
    \nAfter you created a PAT click on Authorize and add your PAT under BearerAuth.\n"
  title: Exasol SaaS REST-API
  version: "1.0"
servers:
- description: Production
  url: https://cloud.exasol.com
tags:
- description: Calls to interact with your database
  name: Databases
- description: Calls to interact with your clusters
  name: Clusters
- description: Calls to get platform information
  name: Platform
- description: Calls to manage users
  name: Users
- description: Get usage
  name: Usage
paths:
  /api/v1/accounts/{accountID}/databases:
    description: Create a new database
    get:
      description: List databases
      operationId: ListDatabases
      security:
      - BearerAuth:
        - databases:use
      summary: List databases
      tags:
      - Databases
    post:
      description: Create a new database
      operationId: CreateDatabase
      security:
      - BearerAuth:
        - databases:operate
      summary: Create database
      tags:
      - Databases
    summary: Create database
  /api/v1/accounts/{accountID}/databases/{databaseID}:
    delete:
      description: Delete the database and all cluster
      operationId: DeleteDatabase
      security:
      - BearerAuth:
        - databases:operate
      summary: Delete database
      tags:
      - Databases
    description: Update database
    get:
      description: Get the database
      operationId: GetDatabase
      security:
      - BearerAuth:
        - databases:use
      summary: Get database
      tags:
      - Databases
    put:
      description: Update database
      operationId: UpdateDatabase
      security:
      - BearerAuth:
        - databases:operate
      summary: Update database
      tags:
      - Databases
    summary: Update database
  /api/v1/accounts/{accountID}/databases/{databaseID}/clusters:
    description: Create a new cluster
    get:
      description: List clusters from a database
      operationId: ListClusters
      security:
      - BearerAuth:
        - databases:use
      summary: List clusters
      tags:
      - Clusters
    post:
      description: Create a new cluster
      operationId: CreateCluster
      security:
      - BearerAuth:
        - databases:operate
      summary: Create cluster
      tags:
      - Clusters
    summary: Create cluster
  /api/v1/accounts/{accountID}/databases/{databaseID}/clusters/{clusterID}:
    delete:
      description: Delete the cluster, if main cluster is deleted, the whole database
        will be deleted.
      operationId: DeleteCluster
      security:
      - BearerAuth:
        - databases:operate
      summary: Delete cluster
      tags:
      - Clusters
    description: |-
      Update the cluster with the specified ID.
       Only metadata can be changed. To scale the cluster size, use the scale cluster endpoint.
    get:
      description: Get cluster
      operationId: GetCluster
      security:
      - BearerAuth:
        - databases:use
      summary: Get cluster
      tags:
      - Clusters
    put:
      description: |-
        Update the cluster with the specified ID.
         Only metadata can be changed. To scale the cluster size, use the scale cluster endpoint.
      operationId: UpdateCluster
      security:
      - BearerAuth:
        - databases:operate
      summary: Update cluster
      tags:
      - Clusters
    summary: Update cluster
  /api/v1/accounts/{accountID}/databases/{databaseID}/clusters/{clusterID}/connect:
    description: Get connection information
    get:
      description: Get connection information
      operationId: GetClusterConnection
      security:
      - BearerAuth:
        - databases:use
      summary: Get connection information
      tags:
      - Clusters
    summary: Get connection information
  /api/v1/accounts/{accountID}/databases/{databaseID}/clusters/{clusterID}/scale:
    description: Scale cluster
    put:
      description: Scale cluster
      operationId: ScaleCluster
      security:
      - BearerAuth:
        - databases:operate
      summary: Scale cluster
      tags:
      - Clusters
    summary: Scale cluster
  /api/v1/accounts/{accountID}/databases/{databaseID}/clusters/{clusterID}/start:
    description: Start cluster
    put:
      description: Start cluster
      operationId: StartCluster
      security:
      - BearerAuth:
        - databases:operate
      summary: Start cluster
      tags:
      - Clusters
    summary: Start cluster
  /api/v1/accounts/{accountID}/databases/{databaseID}/clusters/{clusterID}/stop:
    description: Stop cluster
    put:
      description: Stop cluster
      operationId: StopCluster
      security:
      - BearerAuth:
        - databases:operate
      summary: Stop cluster
      tags:
      - Clusters
    summary: Stop cluster
  /api/v1/accounts/{accountID}/databases/{databaseID}/start:
    description: |-
      Start database
      If database is from type main, workers will be also started
    put:
      description: |-
        Start database
        If database is from type main, workers will be also started
      operationId: StartDatabase
      security:
      - BearerAuth:
        - databases:operate
      summary: Start database
      tags:
      - Databases
    summary: Start database
  /api/v1/accounts/{accountID}/databases/{databaseID}/stop:
    description: |-
      Stop database
      If database is from type main, workers will be also stopped
    put:
      description: |-
        Stop database
        If database is from type main, workers will be also stopped
      operationId: StopDatabase
      security:
      - BearerAuth:
        - databases:operate
      summary: Stop database
      tags:
      - Databases
    summary: Stop database
  /api/v1/accounts/{accountID}/security/allowlist_ip:
    description: Add security rule to allow access from CIDR
    get:
      description: List security rules (CIDR)
      operationId: ListAllowedIPs
      security:
      - BearerAuth:
        - security:read
      summary: List security rules (CIDR)
      tags:
      - Security
    post:
      description: Add security rule to allow access from CIDR
      operationId: AddAllowedIP
      security:
      - BearerAuth:
        - security:write
      summary: Add security rule (CIDR)
      tags:
      - Security
    summary: Add security rule (CIDR)
  /api/v1/accounts/{accountID}/security/allowlist_ip/{ID}:
    delete:
      description: Delete security rule (CIDR). No access to database possible after
        deletion from CIDR
      operationId: DeleteAllowedIP
      security:
      - BearerAuth:
        - security:write
      summary: Delete security rule (CIDR)
      tags:
      - Security
    description: Delete security rule (CIDR). No access to database possible after
      deletion from CIDR
    get:
      description: Get security rule (CIDR)
      operationId: GetAllowedIP
      security:
      - BearerAuth:
        - security:read
      summary: Get security rule (CIDR)
      tags:
      - Security
    put:
      description: Update security rule (CIDR)
      operationId: UpdateAllowedIP
      security:
      - BearerAuth:
        - security:write
      summary: Update security rule (CIDR)
      tags:
      - Security
    summary: Delete security rule (CIDR)
  /api/v1/accounts/{accountID}/usage:
    description: Show usage for one month
    get:
      description: Show usage for one month
      operationId: GetUsage
      security:
      - BearerAuth:
        - users:read
      summary: Get usage
      tags:
      - Usage
    summary: Get usage
  /api/v1/accounts/{accountID}/users:
    description: List users for account
    get:
      description: List users for account
      operationId: ListUsers
      security:
      - BearerAuth:
        - users:read
      summary: List users
      tags:
      - Users
    summary: List users
  /api/v1/accounts/{accountID}/users/{userID}:
    delete:
      description: Remove user from account
      operationId: DeleteUser
      security:
      - BearerAuth:
        - users:write
      summary: Remove user
      tags:
      - Users
    description: Remove user from account
    patch:
      description: Patch user
      operationId: PatchUser
      security:
      - BearerAuth:
        - users:write
      summary: Patch user
      tags:
      - Users
    put:
      description: Update user
      operationId: UpdateUser
      security:
      - BearerAuth:
        - users:write
      summary: Update user
      tags:
      - Users
    summary: Remove user
  /api/v1/platforms:
    description: Get available platforms
    get:
      description: Get available platforms
      operationId: ListPlatforms
      security:
      - BearerAuth: []
      summary: List platforms
      tags:
      - Platform
    summary: List platforms
  /api/v1/platforms/{platform}/regions:
    description: Get available regions for platform
    get:
      description: Get available regions for platform
      operationId: ListRegions
      security:
      - BearerAuth: []
      summary: Get regions for platform
      tags:
      - Platform
    summary: Get regions for platform
  /api/v1/platforms/{platform}/sizes:
    description: Get available cluster sizes for platform
    get:
      description: Get available cluster sizes for platform
      operationId: ListClusterSizes
      security:
      - BearerAuth: []
      summary: Get cluster sizes for platform
      tags:
      - Platform
    summary: Get cluster sizes for platform
components:
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
